language: node_js
node_js:
- stable
branchs:
  only:
  - develop
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 45.32.33.18
before_install:
- openssl aes-256-cbc -K $encrypted_574f1c23860c_key -iv $encrypted_574f1c23860c_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
install:
- yarn install
scripts:
- yarn test
- yarn build
after_success:
- chmod 600 ~/.ssh/id_rsa_travis
- ssh root@45.32.33.18 -o StrictHostKeyChecking=no
